###################################################################################################
# Commented and pretified version of what is generated by install.sh in the gensync function      #
###################################################################################################

#!/bin/bash
# Get the date and get it to $dat
dat=`date +%d-%m-%y`
# Path set by install.sh in $install_location
path=/home/alona
# Path set by install.sh in $backup_location
bac=/home/alona/dropbox_backup
# Path set by install.sh in $dropbox_folder
dropbx=/home/alona/Dropbox
function sync() {
if [ ! -d $path/$bac/ ]; then
  mkdir $path/$bac
  sync() # script just exits if you don't call this 
elif [ ! -d $path/$bac/$dat]; then 
  # Make a directory for the day
  mkdir $path/$bac/$dat
  # Copy all files from Dropbox folder to backup folder
  cp -r $path/$dropbx $path/$bac/$dat 
  # Compress the file that we just made
  tar -czvf $path/$bac/$dat.tar.gz $path/$bac/$dat/
  # Delete uncompressed files 
  rm -rf $path/$bac/$dat
else # we don't want this running more than once per day.
  exit
fi
}
